# Generated by Django 5.2.5 on 2026-01-31 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_systemsettings_websitesettings_remove_user_is_client_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='company_name',
            new_name='school_name',
        ),
        migrations.RemoveField(
            model_name='client',
            name='company_logo',
        ),
        migrations.RemoveField(
            model_name='client',
            name='gst_number',
        ),
        migrations.AddField(
            model_name='client',
            name='can_create_idcard',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='client',
            name='can_delete_idcard',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='client',
            name='can_download_idcard',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='client',
            name='can_edit_idcard',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='client',
            name='can_manage_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='client',
            name='can_print_idcard',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='client',
            name='can_view_reports',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='client',
            name='contact_person_designation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='contact_person_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='school_logo',
            field=models.ImageField(blank=True, null=True, upload_to='school_logos/'),
        ),
    ]
