# Generated by Django 5.2.5 on 2026-01-31 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_school_name_client_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='perm_idcard_setting_add',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='staff',
            name='perm_idcard_setting_delete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='staff',
            name='perm_idcard_setting_edit',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='staff',
            name='perm_idcard_setting_list',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='staff',
            name='perm_idcard_setting_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='staff',
            name='perm_staff_add',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='staff',
            name='perm_staff_delete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='staff',
            name='perm_staff_edit',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='staff',
            name='perm_staff_list',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='staff',
            name='perm_staff_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='client',
            name='perm_idcard_add',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='client',
            name='perm_idcard_created_at',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='client',
            name='perm_idcard_edit',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='client',
            name='perm_idcard_info',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='client',
            name='perm_idcard_pending_list',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='client',
            name='perm_idcard_retrieve',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='client',
            name='perm_idcard_updated_at',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='client',
            name='perm_idcard_verified_list',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='client',
            name='perm_idcard_verify',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='client',
            name='perm_staff_list',
            field=models.BooleanField(default=False),
        ),
    ]
