# Generated by Django 5.2.5 on 2026-02-01 10:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_staff_address_staff_perm_idcard_setting_add_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IDCardTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('fields', models.JSONField(default=list, help_text='List of field configurations: [{name, type, order}]')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tables', to='core.idcardgroup')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
