# Generated by Django 5.2.5 on 2026-02-01 14:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_idcardtable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='idcard',
            name='address',
        ),
        migrations.RemoveField(
            model_name='idcard',
            name='blood_group',
        ),
        migrations.RemoveField(
            model_name='idcard',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='idcard',
            name='date_of_joining',
        ),
        migrations.RemoveField(
            model_name='idcard',
            name='department',
        ),
        migrations.RemoveField(
            model_name='idcard',
            name='designation',
        ),
        migrations.RemoveField(
            model_name='idcard',
            name='email',
        ),
        migrations.RemoveField(
            model_name='idcard',
            name='employee_id',
        ),
        migrations.RemoveField(
            model_name='idcard',
            name='employee_name',
        ),
        migrations.RemoveField(
            model_name='idcard',
            name='group',
        ),
        migrations.RemoveField(
            model_name='idcard',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='idcard',
            name='valid_from',
        ),
        migrations.RemoveField(
            model_name='idcard',
            name='valid_until',
        ),
        migrations.AddField(
            model_name='idcard',
            name='field_data',
            field=models.JSONField(default=dict, help_text='Dynamic field values based on table fields'),
        ),
        migrations.AddField(
            model_name='idcard',
            name='table',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='id_cards', to='core.idcardtable'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='idcard',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('pool', 'In Pool'), ('approved', 'Approved'), ('download', 'Downloaded'), ('reprint', 'Reprint')], default='pending', max_length=20),
        ),
    ]
