# Generated by Django 5.2.10 on 2026-02-03 09:08

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_updated_idcard_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='image_folder_uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name='idcard',
            name='original_photo_name',
            field=models.CharField(blank=True, help_text='Original photo name from Excel for matching', max_length=255, null=True),
        ),
    ]
