# Generated by Django 5.2.5 on 2026-02-03 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_add_uuid_and_photo_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='image_folder_code',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='client',
            name='image_folder_suffix',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
